# Have to use NODE 18 with the from command for the base image
FROM node:18-bullesye

# Setting the working directory
WORKDIR /usr/local/app

# Copying the application now
COPY ./angular-site /usr/local/app
